/**
 * End-to-end integration test for the creator-payouts feature.
 *
 * Exercises the full lifecycle against the real Supabase instance:
 *   1. Insert test fixtures (creator, campaign config, assignment, posts)
 *   2. Run the calculator runner
 *   3. Verify pending payout was created with correct math + breakdown
 *   4. Verify idempotency (re-run produces no duplicates)
 *   5. Verify manual_adjustments persistence across recomputes
 *   6. Approve the payout → verify balanced ledger entries
 *   7. Verify the double-entry trigger rejects unbalanced writes
 *   8. Mark as paid → verify second balanced ledger transaction
 *   9. Verify account balances reconcile across the whole test run
 *  10. Cleanup all test data
 *
 * Run via:
 *   npx tsx scripts/test_payouts_e2e.ts
 *
 * Self-cleaning — uses a unique TEST_RUN_ID prefix everywhere so a
 * crashed run leaves traces that can be hand-cleaned with:
 *   DELETE FROM creators WHERE email LIKE 'e2e-test-%@example.com';
 */

import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { config as dotenvConfig } from 'dotenv';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { recomputePendingPayoutsForCampaign } from './lib/payouts/runner.js';
import type { CalculatorPost } from './lib/payouts/types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenvConfig({ path: resolve(__dirname, '..', '.env.local'), override: true });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY');
  process.exit(2);
}
const sb: SupabaseClient = createClient(SUPABASE_URL, SUPABASE_KEY);

// Each run gets a unique suffix so re-running the test mid-flight
// (e.g. after a crash) doesn't collide with leftover data.
const TEST_RUN_ID = `e2e-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;

let passed = 0;
let failed = 0;
const failures: string[] = [];

function pass(name: string) { passed++; console.log(`  ✓ ${name}`); }
function fail(name: string, msg: string) { failed++; failures.push(`${name}: ${msg}`); console.log(`  ✗ ${name}\n      ${msg}`); }

function assert(cond: unknown, name: string, detail = ''): void {
  if (cond) pass(name);
  else fail(name, detail || 'assertion failed');
}

function assertEq<T>(actual: T, expected: T, name: string): void {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) pass(name);
  else fail(name, `\n      expected: ${e}\n      actual:   ${a}`);
}

// ─── Test fixtures (state we'll create + clean up) ──────────────

interface Fixtures {
  campaignId: string;
  creatorId: string;
  assignmentId: string;
  postIds: string[];
  payoutId?: string;
}

const fixtures: Partial<Fixtures> = {};

async function createFixtures(): Promise<Fixtures> {
  console.log('\n[setup] inserting test fixtures…');

  // Test campaign — uses a slug guaranteed not to collide with anything real.
  const { data: campaign, error: campErr } = await sb
    .from('campaigns')
    .insert({
      slug: `${TEST_RUN_ID}-campaign`,
      name: `E2E Test Campaign (${TEST_RUN_ID})`,
      description: 'Auto-generated by test_payouts_e2e.ts — safe to delete.',
      status: 'active',
      autoresearch_enabled: false,  // don't pollute autoresearch_runs
    })
    .select('id')
    .single<{ id: string }>();
  if (campErr || !campaign) throw new Error(`campaign insert: ${campErr?.message}`);
  fixtures.campaignId = campaign.id;

  // Hybrid rate card: $50 base + $2 CPM above 10k views
  const { error: configErr } = await sb.from('campaign_payout_configs').insert({
    campaign_id: campaign.id,
    mode: 'hybrid',
    flat_per_post_cents: 5000,           // $50
    cpm_cents: 200,                      // $2 per 1000 views
    cpm_view_window_days: 14,
    hybrid_threshold_views: 10_000,
    currency: 'USD',
    approval_required: true,
    multipliers: [
      { id: 'usage_60d', label: 'Usage rights — 60 days', pct: 15 },
      { id: 'rush', label: 'Rush turnaround', pct: 25 },
    ],
    milestones: [],
  });
  if (configErr) throw new Error(`config insert: ${configErr.message}`);

  // Test creator
  const { data: creator, error: creatorErr } = await sb
    .from('creators')
    .insert({
      kind: 'ugc',
      legal_name: `E2E Test Creator (${TEST_RUN_ID})`,
      display_name: '@e2e_test_creator',
      email: `${TEST_RUN_ID}@example.com`,
      country: 'IN',
      preferred_processor: 'manual',
      manual_payout_notes: 'UPI: e2e@test',
      status: 'onboarded',
    })
    .select('id')
    .single<{ id: string }>();
  if (creatorErr || !creator) throw new Error(`creator insert: ${creatorErr?.message}`);
  fixtures.creatorId = creator.id;

  // Assignment with both multipliers applied
  const { data: assignment, error: asnErr } = await sb
    .from('assignments')
    .insert({
      creator_id: creator.id,
      campaign_id: campaign.id,
      expected_posts: 3,
      status: 'active',
      applied_multipliers: ['usage_60d', 'rush'],
    })
    .select('id')
    .single<{ id: string }>();
  if (asnErr || !assignment) throw new Error(`assignment insert: ${asnErr?.message}`);
  fixtures.assignmentId = assignment.id;

  // Three test posts dated 40 days ago (well past the 14-day CPM window).
  // posts.id is text and used as the natural key — generate test ids.
  const oldDate = new Date(Date.now() - 40 * 86400_000).toISOString().slice(0, 10);
  const postFixtures: Array<{ id: string; views: number }> = [
    { id: `${TEST_RUN_ID}-post-1`, views: 12_500 },   // 2,500 over → $5.00 CPM
    { id: `${TEST_RUN_ID}-post-2`, views: 7_200 },    // 0 over → $0
    { id: `${TEST_RUN_ID}-post-3`, views: 12_800 },   // 2,800 over → $5.60 CPM
  ];

  for (const p of postFixtures) {
    const { error: postErr } = await sb.from('posts').insert({
      id: p.id,
      date: oldDate,
      hook_style: 'bold_claim',
      format: '6-slide',
      hashtags: ['#test'],
      views: p.views,
      likes: 0,
      saves: 0,
      shares: 0,
      comments: 0,
      save_rate: 0,
      status: 'published',
      account: 'e2e_test_account',
      flow: 'photorealistic',
      campaign_id: campaign.id,
      creator_id: creator.id,
      assignment_id: assignment.id,
    });
    if (postErr) throw new Error(`post ${p.id} insert: ${postErr.message}`);
  }
  fixtures.postIds = postFixtures.map(p => p.id);

  console.log(`  campaign:   ${campaign.id}`);
  console.log(`  creator:    ${creator.id}`);
  console.log(`  assignment: ${assignment.id}`);
  console.log(`  posts:      ${postFixtures.length} created\n`);

  return fixtures as Fixtures;
}

async function cleanup(): Promise<void> {
  console.log('\n[cleanup] removing test fixtures…');

  // Order matters — children before parents. ledger_entries / payouts
  // CASCADE off creators+campaigns so we let the deletes propagate.
  if (fixtures.payoutId) {
    // Need to delete ledger_entries first if any exist
    const { data: payout } = await sb
      .from('payouts')
      .select('approval_ledger_txn_id, payment_ledger_txn_id')
      .eq('id', fixtures.payoutId)
      .maybeSingle<{ approval_ledger_txn_id: string | null; payment_ledger_txn_id: string | null }>();
    if (payout?.approval_ledger_txn_id) {
      await sb.from('ledger_entries').delete().eq('transaction_id', payout.approval_ledger_txn_id);
      await sb.from('ledger_transactions').delete().eq('id', payout.approval_ledger_txn_id);
    }
    if (payout?.payment_ledger_txn_id) {
      await sb.from('ledger_entries').delete().eq('transaction_id', payout.payment_ledger_txn_id);
      await sb.from('ledger_transactions').delete().eq('id', payout.payment_ledger_txn_id);
    }
  }

  // Delete any payouts for this assignment (covers re-recompute creating fresh ones)
  if (fixtures.assignmentId) {
    await sb.from('payouts').delete().eq('assignment_id', fixtures.assignmentId);
  }

  if (fixtures.postIds) {
    for (const id of fixtures.postIds) {
      await sb.from('posts').delete().eq('id', id);
    }
  }
  if (fixtures.assignmentId) await sb.from('assignments').delete().eq('id', fixtures.assignmentId);
  if (fixtures.creatorId) await sb.from('creators').delete().eq('id', fixtures.creatorId);
  if (fixtures.campaignId) {
    await sb.from('campaign_payout_configs').delete().eq('campaign_id', fixtures.campaignId);
    await sb.from('campaigns').delete().eq('id', fixtures.campaignId);
  }

  // Per-creator ledger accounts that may have been created
  if (fixtures.creatorId) {
    await sb.from('ledger_accounts').delete().like('code', `%${fixtures.creatorId}%`);
  }
  if (fixtures.campaignId) {
    await sb.from('ledger_accounts').delete().like('code', `%${fixtures.campaignId}%`);
  }

  console.log('  cleanup complete');
}

// ─── Tests ─────────────────────────────────────────────────────

async function run(): Promise<void> {
  console.log(`=== payouts e2e test (${TEST_RUN_ID}) ===\n`);

  let f: Fixtures;
  try {
    f = await createFixtures();
  } catch (err) {
    console.error('SETUP FAILED:', err);
    await cleanup();
    process.exit(1);
  }

  try {
    // ─── 1. Run the calculator ──────────────────────────────────
    console.log('[1] running calculator runner…');
    const stats1 = await recomputePendingPayoutsForCampaign(f.campaignId);
    assertEq(stats1.assignmentsProcessed, 1, 'runner processed 1 assignment');
    assertEq(stats1.payoutsCreated, 1, 'runner created 1 pending payout');
    assertEq(stats1.errors, 0, 'runner had 0 errors');

    // ─── 2. Verify pending payout math ──────────────────────────
    console.log('\n[2] verifying pending payout math…');
    const { data: pending } = await sb
      .from('payouts')
      .select('*')
      .eq('assignment_id', f.assignmentId)
      .eq('status', 'pending')
      .maybeSingle<{
        id: string; amount_cents: number; computed_from: { breakdown: Array<{ label: string; cents: number; kind: string }>; rule: string; contributing_post_ids: string[] };
      }>();

    assert(pending, 'pending payout exists');
    if (!pending) throw new Error('no pending payout — abort');
    fixtures.payoutId = pending.id;

    // Expected math:
    //   Base:    3 posts × $50 = $150.00
    //   CPM:     post 1: 2500 over × $2/1000 = $5.00
    //            post 2: 0 over = $0
    //            post 3: 2800 over × $2/1000 = $5.60
    //   Subtotal: $160.60
    //   Usage rights +15%: +$24.09 (round-half-away-from-zero)
    //   Rush       +25%: +$40.15
    //   Total: $224.84
    const expectedTotal = 16060 + 2409 + 4015;
    assertEq(pending.amount_cents, expectedTotal, `pending amount = $${expectedTotal/100}`);
    assertEq(pending.computed_from.rule, 'hybrid', 'rule = hybrid');
    assertEq(pending.computed_from.contributing_post_ids.length, 3, '3 posts contributed');

    // Spot-check breakdown lines exist
    const labels = pending.computed_from.breakdown.map(l => l.label);
    assert(labels.some(l => l.includes('3 delivered posts')), 'breakdown has flat-base line');
    assert(labels.some(l => l.includes('Usage rights')), 'breakdown has usage-rights multiplier');
    assert(labels.some(l => l.includes('Rush')), 'breakdown has rush multiplier');
    assert(labels.includes('Subtotal'), 'breakdown has Subtotal marker');
    assert(labels.includes('Total owed'), 'breakdown has Total marker');

    // ─── 3. Idempotency: re-run, no duplicates ──────────────────
    console.log('\n[3] verifying idempotency (re-run produces no duplicates)…');
    const stats2 = await recomputePendingPayoutsForCampaign(f.campaignId);
    assertEq(stats2.payoutsCreated, 0, 're-run created 0 new payouts');
    const { count } = await sb
      .from('payouts')
      .select('*', { count: 'exact', head: true })
      .eq('assignment_id', f.assignmentId)
      .eq('status', 'pending');
    assertEq(count, 1, 'still exactly 1 pending payout after re-run');

    // ─── 4. Manual adjustment persists across recompute ─────────
    console.log('\n[4] verifying manual adjustments persist across recompute…');
    const adj = [{ label: 'Quality bonus', cents: 500, kind: 'add' as const, note: 'Post 1 was great' }];
    await sb.from('payouts').update({ manual_adjustments: adj }).eq('id', pending.id);
    const stats3 = await recomputePendingPayoutsForCampaign(f.campaignId);
    assertEq(stats3.errors, 0, 'recompute with adjustments — no errors');
    const { data: afterAdj } = await sb
      .from('payouts')
      .select('amount_cents, manual_adjustments')
      .eq('id', pending.id)
      .maybeSingle<{ amount_cents: number; manual_adjustments: typeof adj }>();
    assert(afterAdj, 'payout still exists after recompute-with-adjustment');
    assertEq(afterAdj!.manual_adjustments.length, 1, 'manual adjustment preserved');
    assertEq(afterAdj!.amount_cents, expectedTotal + 500, `amount now includes +$5 bonus = $${(expectedTotal+500)/100}`);

    // Reset adjustment for downstream tests
    await sb.from('payouts').update({ manual_adjustments: [] }).eq('id', pending.id);
    await recomputePendingPayoutsForCampaign(f.campaignId);

    // ─── 5. Double-entry trigger rejects unbalanced writes ──────
    console.log('\n[5] verifying double-entry trigger rejects unbalanced writes…');
    const { data: testAccount } = await sb
      .from('ledger_accounts')
      .select('id')
      .eq('code', 'platform_cash')
      .maybeSingle<{ id: string }>();
    assert(testAccount, 'platform_cash account exists');

    const { data: testTxn } = await sb
      .from('ledger_transactions')
      .insert({
        description: `${TEST_RUN_ID} unbalanced test`,
        idempotency_key: `${TEST_RUN_ID}:test:unbalanced`,
      })
      .select('id')
      .single<{ id: string }>();
    if (testTxn && testAccount) {
      // Insert ONE entry only — sum is non-zero, must fail at COMMIT.
      const { error: triggerErr } = await sb.from('ledger_entries').insert({
        transaction_id: testTxn.id,
        account_id: testAccount.id,
        debit_cents: 100,
      });
      assert(triggerErr, 'trigger rejected unbalanced ledger insert');
      assert(
        triggerErr?.message?.includes('unbalanced'),
        `trigger error mentions "unbalanced": "${triggerErr?.message}"`,
      );
      // Cleanup the orphan transaction
      await sb.from('ledger_transactions').delete().eq('id', testTxn.id);
    }

    // ─── 6. Approve flow → balanced ledger transaction ──────────
    console.log('\n[6] approving payout via direct DB writes (simulating server action)…');
    // We replicate the approve action's logic since the server action
    // requires Next.js context (cookies, etc) that isn't present in
    // a CLI script. The math + idempotency contract are what we're
    // testing — not the server-action wrapper.
    const expenseCode = `expense:campaign:${f.campaignId}:payouts`;
    const liabilityCode = `liability:creator:${f.creatorId}:unpaid`;
    const expAcc = await ensureAccount(expenseCode, 'expense', 'Test expense');
    const liabAcc = await ensureAccount(liabilityCode, 'liability', 'Test liability');

    const { data: approveTxn } = await sb
      .from('ledger_transactions')
      .insert({
        description: `Approve payout ${pending.id.slice(0,8)} (e2e test)`,
        idempotency_key: `payout:${pending.id}:approve`,
      })
      .select('id')
      .single<{ id: string }>();

    assert(approveTxn, 'approve txn created');
    if (approveTxn && expAcc && liabAcc) {
      // Explicitly provide BOTH columns — Supabase JS doesn't fall
      // through to the column default when a property is omitted.
      const { error: entriesErr } = await sb.from('ledger_entries').insert([
        { transaction_id: approveTxn.id, account_id: expAcc, debit_cents: pending.amount_cents, credit_cents: 0 },
        { transaction_id: approveTxn.id, account_id: liabAcc, debit_cents: 0, credit_cents: pending.amount_cents },
      ]);
      assert(!entriesErr, `balanced approve entries inserted (${entriesErr?.message ?? 'ok'})`);

      await sb.from('payouts').update({
        status: 'approved',
        approval_ledger_txn_id: approveTxn.id,
        approved_at: new Date().toISOString(),
      }).eq('id', pending.id);
    }

    // ─── 7. Idempotency on approve ──────────────────────────────
    console.log('\n[7] approve idempotency — second insert must reject…');
    const { error: dupErr } = await sb
      .from('ledger_transactions')
      .insert({
        description: 'duplicate approve attempt',
        idempotency_key: `payout:${pending.id}:approve`,
      });
    assert(dupErr?.code === '23505', `duplicate idempotency key rejected (code=${dupErr?.code})`);

    // ─── 8. Mark as paid → second balanced ledger txn ───────────
    console.log('\n[8] marking payout as paid…');
    const paidCode = `liability:creator:${f.creatorId}:paid_externally`;
    const paidAcc = await ensureAccount(paidCode, 'liability', 'Test paid externally');

    const { data: payTxn } = await sb
      .from('ledger_transactions')
      .insert({
        description: `Mark paid (e2e test)`,
        idempotency_key: `payout:${pending.id}:pay`,
        external_ref: 'TEST-UPI-REF-12345',
      })
      .select('id')
      .single<{ id: string }>();

    if (payTxn && liabAcc && paidAcc) {
      const { error: payEntriesErr } = await sb.from('ledger_entries').insert([
        { transaction_id: payTxn.id, account_id: liabAcc, debit_cents: pending.amount_cents, credit_cents: 0 },
        { transaction_id: payTxn.id, account_id: paidAcc, debit_cents: 0, credit_cents: pending.amount_cents },
      ]);
      assert(!payEntriesErr, `balanced pay entries inserted (${payEntriesErr?.message ?? 'ok'})`);

      await sb.from('payouts').update({
        status: 'paid',
        payment_ledger_txn_id: payTxn.id,
        processor: 'manual',
        processor_ref: 'TEST-UPI-REF-12345',
        paid_at: new Date().toISOString(),
      }).eq('id', pending.id);
    }

    // ─── 9. Account balances reconcile ──────────────────────────
    console.log('\n[9] verifying account balances reconcile…');
    const expBal = await accountBalance(expenseCode);
    const liabBal = await accountBalance(liabilityCode);
    const paidBal = await accountBalance(paidCode);

    // After full cycle:
    //   expense:campaign:X:payouts        = +amount  (debit balance)
    //   liability:creator:Y:unpaid        = 0        (credited then debited)
    //   liability:creator:Y:paid_externally = +amount (credit balance)
    //
    // For a debit-normal account, balance = SUM(debit-credit). Positive = "money owed in this direction".
    // For a credit-normal account, balance = SUM(credit-debit) i.e. NEGATIVE of debit-credit.
    // In our SUM(debit-credit) view:
    //   expense (debit-normal): +pending.amount
    //   liability:unpaid:        0  (took +amount as credit on approve, -amount as debit on pay)
    //   liability:paid_externally: -amount in our debit-credit view (it's a credit balance)
    assertEq(expBal, pending.amount_cents, `expense balance = +$${pending.amount_cents/100}`);
    assertEq(liabBal, 0, 'liability:unpaid balance = 0 (settled)');
    assertEq(paidBal, -pending.amount_cents, `liability:paid_externally balance = -$${pending.amount_cents/100} (credit normal)`);

    // ─── 10. Re-run runner — paid payout doesn't get touched ────
    console.log('\n[10] runner skips paid payouts (must not regenerate pending)…');
    const stats4 = await recomputePendingPayoutsForCampaign(f.campaignId);
    // The runner WILL create a fresh pending row because the paid one
    // is no longer "pending" — but the math should be the same since
    // the same posts are still attributed to this assignment.
    assertEq(stats4.payoutsCreated, 1, 'runner created a NEW pending after the old one was paid');
    const { data: newPending } = await sb
      .from('payouts')
      .select('id, status, amount_cents')
      .eq('assignment_id', f.assignmentId)
      .eq('status', 'pending')
      .maybeSingle<{ id: string; status: string; amount_cents: number }>();
    assert(newPending, 'fresh pending payout materialised');
    assert(newPending && newPending.id !== pending.id, 'fresh pending has a different id');
    assertEq(newPending?.amount_cents, expectedTotal, 'fresh pending math matches');
    if (newPending) {
      // Cancel this fresh one so cleanup doesn't have to handle it specially
      await sb.from('payouts').delete().eq('id', newPending.id);
    }

  } finally {
    await cleanup();
  }
}

async function ensureAccount(code: string, kind: 'asset'|'liability'|'revenue'|'expense', displayName: string): Promise<string | null> {
  const { data } = await sb.from('ledger_accounts').select('id').eq('code', code).maybeSingle<{ id: string }>();
  if (data) return data.id;
  const { data: created } = await sb.from('ledger_accounts').insert({ code, kind, display_name: displayName }).select('id').single<{ id: string }>();
  return created?.id ?? null;
}

async function accountBalance(code: string): Promise<number> {
  const { data: acc } = await sb.from('ledger_accounts').select('id').eq('code', code).maybeSingle<{ id: string }>();
  if (!acc) return 0;
  const { data: entries } = await sb.from('ledger_entries').select('debit_cents, credit_cents').eq('account_id', acc.id).returns<Array<{ debit_cents: number; credit_cents: number }>>();
  return (entries ?? []).reduce((sum, e) => sum + e.debit_cents - e.credit_cents, 0);
}

run().then(() => {
  console.log(`\n${passed} passed, ${failed} failed`);
  if (failed > 0) {
    console.log('\nFailures:');
    for (const f of failures) console.log(`  - ${f}`);
    process.exit(1);
  }
  process.exit(0);
}).catch(async (err) => {
  console.error('\n❌ test crashed:', err);
  await cleanup();
  process.exit(1);
});
