import "server-only";

import type { CreddyBankItemDto } from "@/lib/creddy-file-store";
import { createClient } from "@/lib/supabase";

const TABLE = "creddy_content_bank";
const BUCKET = "creddy-content";

type CloudAssets = {
  slides?: string[];
  text_music?: string;
  narrated?: string;
};

type CloudRow = {
  id: string;
  item: CreddyBankItemDto;
  assets: CloudAssets;
};

export async function listCreddyCloudBankItems(): Promise<CreddyBankItemDto[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from(TABLE)
    .select("id,item,synced_at")
    .order("synced_at", { ascending: false });

  // Deploying the code before its migration should leave the existing empty
  // state intact rather than taking down the whole dashboard.
  if (error) {
    console.warn(`Creddy cloud mirror is unavailable: ${error.message}`);
    return [];
  }

  return (data ?? []).map((row) => ({
    ...(row.item as CreddyBankItemDto),
    cloudBacked: true,
    // Slide design changes are generated by the Mac pipeline. The deployed
    // mirror is deliberately review-only so it cannot fork the source files.
    slideEditor: undefined,
  }));
}

export async function downloadCreddyCloudAsset(input: {
  id: string;
  kind: "slide" | "text_music" | "narrated";
  slide?: number;
}): Promise<{ body: ArrayBuffer; mime: string; size: number }> {
  const supabase = await createClient();
  const { data: row, error: rowError } = await supabase
    .from(TABLE)
    .select("id,assets")
    .eq("id", input.id)
    .single<Pick<CloudRow, "id" | "assets">>();
  if (rowError || !row) throw new Error("Creddy cloud content item not found");

  const path = input.kind === "slide"
    ? row.assets.slides?.[(input.slide ?? 0) - 1]
    : row.assets[input.kind];
  if (!path) throw new Error("Creddy cloud asset not found");

  const { data, error } = await supabase.storage.from(BUCKET).download(path);
  if (error || !data) throw new Error(error?.message ?? "Creddy cloud asset download failed");
  return { body: await data.arrayBuffer(), mime: data.type || "application/octet-stream", size: data.size };
}

